query GetContactDetail($userID: ID!) {
  contactDetail(id: $userID) {
    data {
      id
      attributes {
        firstName
        lastName
        aboutMe
        address {
          postcode
        }
      }
    }
  }
}
