import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { MdHome } from "react-icons/md";
import { useRouter } from "next/router";
import { signIn, useSession } from "next-auth/react";
import { useQuery } from "react-query";
import UserRoles from "@utils/userRoles.";
import GoogleSignInButton from "@components/GoogleSignInButton";
import getContactDetails from "api/getContactDetails";

const Login: React.FC = () => {
  const router = useRouter();
  const session = useSession();
  const { data: contactDetails, isLoading: contactDetailsLoading } = useQuery(
    "getContactDetails",
    getContactDetails
  );

  const handleSignIn = () => {
    signIn("google", {
      userRole: UserRoles.JOB_SEEKER,
    });
  };

  React.useEffect(() => {
    if (session.data && !contactDetailsLoading) {
      console.log(contactDetails);
      if (session.data.isNewUser || contactDetails?.data.data.length === 0)
        router.replace("/auth/completeProfile");
      else {
        if (session.data.user.role?.name === UserRoles.JOB_SEEKER)
          router.replace("/seeker/dashboard");
        if (session.data.user.role?.name === UserRoles.JOB_PROVIDER)
          router.replace("/provider/dashboard");
      }
    }
  }, [router, session, contactDetails, contactDetailsLoading]);

  return (
    <div className="flex h-screen items-center justify-center">
      <Head>
        <title>Britjobs | Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="absolute top-5 left-5 z-10">
        <Link href="/" passHref>
          <button className="btn btn-circle btn-lg">
            <MdHome className="text-3xl" />
          </button>
        </Link>
      </div>

      <div className="card w-3/12 min-w-fit bg-base-200 p-10">
        <GoogleSignInButton onClick={() => handleSignIn()} />
      </div>
    </div>
  );
};

export default Login;
