import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { MdHome, MdError } from "react-icons/md";
import { FcGoogle } from "react-icons/fc";
import keyGen from "@utils/genKey";
import { useRouter } from "next/router";
import { signIn } from "next-auth/react";
import UserRoles from "@utils/userRoles.";

const Login: React.FC = () => {
  const router = useRouter();

  const handleSignIn = () => {
    signIn("google", {
      userRole: UserRoles.JOB_SEEKER,
    });
  };

  return (
    <div className="flex h-screen items-center justify-center">
      <Head>
        <title>Britjobs | Login</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="absolute top-5 left-5 z-10">
        <Link href="/" passHref>
          <button className="btn btn-circle btn-lg">
            <MdHome className="text-3xl" />
          </button>
        </Link>
      </div>

      <div className="card bg-base-200 w-3/12 p-10">
        <button
          className="btn bg-primary-content hover:bg-primary-content flex justify-center gap-4"
          onClick={() => handleSignIn()}
        >
          <FcGoogle className="text-3xl" />
          <span className="text-base-100">Sign-in with Google</span>
        </button>
      </div>
    </div>
  );
};

export default Login;
