import * as React from "react";
import Head from "next/head";
import Link from "next/link";
import { MdHome } from "react-icons/md";

const Register: React.FC = ({ children }) => {
  return (
    <div className="flex justify-center items-center h-screen">
      <Head>
        <title>Britjobs | Register</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="absolute z-10 top-5 left-5">
        <Link href="/" passHref>
          <button className="btn btn-lg btn-circle">
            <MdHome className="text-3xl" />
          </button>
        </Link>
      </div>

      <div className="p-10 card bg-base-200 w-3/12">
        <div className="form-control">
          <label className="label">
            <span className="label-text">Email</span>
          </label>
          <input type="email" placeholder="username/email" className="input" />

          <label className="label">
            <span className="label-text">Password</span>
          </label>
          <input type="text" placeholder="Enter your password" className="input" />

          <label className="label">
            <span className="label-text">Confirm Password</span>
          </label>
          <input type="text" placeholder="Enter your password again" className="input" />

          <button className="btn btn-primary mt-5">Register</button>
          <label className="label">
            <span className="label-text-alt text-info cursor-pointer">
              <Link href="/login">Login</Link>
            </span>
          </label>
        </div>
      </div>
    </div>
  );
};

export default Register;
