import { useEffect, useState, useContext } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "@components/Layout";
import { AuthContext } from "src/contexts/AuthContext";
import { useLazyQuery } from "@apollo/client";
import GetContactDetails from "@graphQL/queries/GetContactDetails.gql";
import { GetContactDetailsQuery } from "@graphQL/graphql-operations";

const Dashboard: NextPage = () => {
  const [profileIsIncomplete, setProfileIsIncomplete] = useState(false);
  const { state: authState } = useContext(AuthContext);
  const [runGetContactDetails, { loading, error, data }] =
    useLazyQuery<GetContactDetailsQuery>(GetContactDetails);

  useEffect(() => {
    if (authState.isLogedin) {
      runGetContactDetails({
        variables: {
          userID: authState.userInfo?.id,
        },
      });
    }
  }, [authState, runGetContactDetails]);

  useEffect(() => {
    if (data?.contactDetails?.data && data?.contactDetails?.data.length > 0) {
      setProfileIsIncomplete(false);
    } else {
      if (data !== undefined) setProfileIsIncomplete(true);
    }
  }, [data, loading]);

  return (
    <div>
      <Head>
        <title>Britjobs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        {profileIsIncomplete && (
          <div
            className="bg-info text-base-200 sticky top-0 z-50 flex items-center 
        justify-center gap-5 py-2 font-bold tracking-wider"
          >
            <span>Your profile is incomplete!</span>
            <button className="btn btn-sm btn-primary">Complete Profile</button>
          </div>
        )}
        <Layout>
          <div className="py-10">
            <div className="flex flex-col items-start justify-center">
              {authState.isLogedin && authState.userInfo?.username && (
                <h1 className="text-6xl">Welcome, {authState.userInfo?.username}!</h1>
              )}
            </div>
          </div>
        </Layout>
      </>
    </div>
  );
};

export default Dashboard;
